site_name: CausalBench Tutorial KDD'25  
nav:
  - Home: index.md
  - Preparing: prep.md
  - Documentation: https://docs.causalbench.org

theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true